# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/msm8917-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter j4primelte j6primelte,$(TARGET_DEVICE)),)

endif
